### ISSUE TITLE
Get current state of Lights

### ISSUE THREAD

**Issue by warch** [tomasbedrich/home-assistant-skydance#3]
Thank you so much for your integration. I love it!

Is it possible to fetch the current state (on/off, brightness, color)? Currently HA is not aware of the current state of the lights. This causes some issues when e.g. HA thinks the lights are on but they are off. When i toggle the switch nothing happens and the second toggle turns the light on.

**Comment by tomasbedrich** [comment]
I am glad that you like it. 😊 

Unfortunately, I am not aware of any way how to fetch the current state. Neither the official Skysmart Android application does it (at least according to my findings), therefore I think it is not possible. I suppose it is designed that way, that a Wi-Fi relay is only a transmitter, not being able to receive the signal from other physical remotes thus not being able to maintain overview of the overall state.

It is still valid point, that it shouldn't appear as toggle switch in Home Assistant under these circumstances. I plan to change the appearance [like this](https://github.com/home-assistant/core/issues/12703), as this better fits into the whole ecosystem of Skydance as Home Assistant being just another "physical" remote.

**Comment by tomasbedrich** [comment]
New version 1.1.1 addressing this issue released.
