### ISSUE TITLE
Do you want me to add GitHub Actions?

### ISSUE THREAD

**Issue by KTibow** [tomasbedrich/home-assistant-skydance#4]
If you want, I can add some advanced CI to your repo in a PR. Let me know if you want that. If you do, mind answering these questions:
- Do you want to enable auto-formatting whenever pushed?
- Do you want packaged or independent (I recommend packaged because I can send updates)?

**Comment by tomasbedrich** [comment]
Hi @KTibow, thanks for your offer. I am not really sure what "advanced CI" means. Can you please clarify?
Regarding formatting, this project uses Black. In light of CI, it would be useful to check it's source against it (not reformat it), whether it complies the standard.

**Comment by KTibow** [comment]
> advanced CI

It means that it runs HACS, Hassfest, and flake8.

> (not reformat it)

Sure, I can do that.

Does this sound good?

**Comment by tomasbedrich** [comment]
There is already Hassfest check in place.

The only check you mentioned and I agree it may be useful to add is Python style check. But for that, I want to comply Black formatting style. If you want to make a PR to add a CI script which does so, you are welcome! 👍
