### ISSUE TITLE
Version core-2021.6.3 / doesn't work

### ISSUE THREAD

**Issue by pepppek** [tomasbedrich/home-assistant-skydance#6]
Hi there,
after upgrade core to version 2021.6.3 SKYDANCE integration stop working.
In logs shows me this: 

Logger: homeassistant.setup
Source: setup.py:172 
First occurred: 9:36:25 AM (1 occurrences) 
Last logged: 9:36:25 AM

Setup failed for skydance: Integration not found.

I tried to reinstal it.. with same result. If i downgrade to older version it is still working.
Is there any advice to solve it?
Than you!

**Comment by tomasbedrich** [comment]
Please try to upgrade to 1.1.5.
